# Generated by Django 3.2.6 on 2021-08-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Detail',
            new_name='ContactDetail',
        ),
    ]
