# Generated by Django 3.2.6 on 2021-09-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_personaldetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=500)),
                ('institution', models.CharField(max_length=500)),
                ('started', models.DateField()),
                ('completed', models.DateField()),
                ('score', models.FloatField(blank=True)),
                ('rank', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='contact_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
